function R = buildR(thetaDeg, phiDeg)

        theta = deg2rad(thetaDeg(:)); % elevation
        phi   = deg2rad(phiDeg(:)); % azimtuh

        a = cos(theta).*sin(phi);
        b = cos(theta).*cos(phi);
        c = sin(theta);

        R = [ ...
            a.^2, ...
            b.^2, ...
            c.^2, ...
            2*a.*b, ...
            2*a.*c, ...
            2*b.*c ...
            ];
    end